<a href="https://colab.research.google.com/github/Ajinkyadata/Coursera-sequence-models/blob/master/add_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import glob
import pickle
import numpy as np
from music21 import converter, instrument, note, chord, stream
from keras.models import Sequential
from keras.layers import *
from keras.utils import np_utils
from keras.callbacks import ModelCheckpoint

In [0]:
chars = '0123456789+'

In [0]:
num=len(chars)

In [0]:
char_ind = dict((c,i) for i, c in enumerate(chars))
ind_char=dict((i,c) for i,c in enumerate(chars))

In [0]:
def generate():
  one=np.random.randint(0,100)
  two=np.random.randint(0,100)

  ans=str(one)+str('+')+str(two)
  label=str(one+two)

  return ans, label

In [17]:
generate()

('15+0', '15')

In [0]:
hidden=128
Tx=5

In [30]:
model =Sequential([
                   SimpleRNN(hidden, input_shape=(None,num)),
                   RepeatVector(Tx),
                   SimpleRNN(hidden, return_sequences=True),
                   TimeDistributed(Dense(num ,activation='softmax'))
])

model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',
    metrics=['accuracy'], 
              )

model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_6 (SimpleRNN)     (None, 128)               17920     
_________________________________________________________________
repeat_vector_3 (RepeatVecto (None, 5, 128)            0         
_________________________________________________________________
simple_rnn_7 (SimpleRNN)     (None, 5, 128)            32896     
_________________________________________________________________
time_distributed_2 (TimeDist (None, 5, 11)             1419      
Total params: 52,235
Trainable params: 52,235
Non-trainable params: 0
_________________________________________________________________


In [0]:
#vectorisation

def vec(eg, label):
  x=np.zeros((Tx, num))
  y=np.zeros((Tx, num))

  diff_x= Tx-len(eg)
  diff_y=Tx-len(label)

  for i,c in enumerate(eg):
    x[i+diff_x, char_ind[c]]=1
  for i in range(diff_x):
    x[i,char_ind['0']]=1

  for i,c in enumerate(label):
    y[i+diff_y, char_ind[c]]=1
  for i in range(diff_y):
    y[i,char_ind['0']]=1

    return x,y


In [53]:
egg, lbl= vec('3+43','56')
print(egg)
print(lbl)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]


In [0]:
#devec
def devec(eg):
  result= [ind_char[np.argmax(vec)] for i, vec in enumerate(eg)]
  return ''.join(result)

In [55]:
devec(egg)

'03+43'

In [0]:
#create dataset
def create_data(num_eg=2000):
  x=np.zeros((num_eg, Tx, num))
  y=np.zeros((num_eg, Tx, num))

  for i in range(num_eg):
    q, a = generate()

    x[i],y[i] = vec(q,a)

  return x,y;

In [57]:
xx, yy= create_data()

print(xx.shape)

(2000, 5, 11)


In [61]:
print(devec(xx[9]))

43+63
